before test
Caught errors ErrorGroup with 10 errors and 10 messages:: {msg = 1} ... {msg = 9}
